# Use this config to provide lookup list and field mapping objects to be used in data cleaning script. 


# List of columns to drop from AGOL table
drop_list:
  - Rel_Depth
  - last_edited_date
  - last_edited_user
  - Parent_GUID
  - GlobalID_1
  - isLive
  - OBJECTID
  - Weather
  - Wind
  - Wind_Direction
  - Cloud_Cover
  - Rainfall_24hr
  - Secchi
  - Conductivity
  - CreationDate
  - Creator
  - EditDate
  - Editor


# Columns in AGOL table to pivot
params_list:
  - Water_Temp
  - DO_Percent
  - DO_Concentration
  - Salinity
  - pH
  - Turbidity
  - Chl_a
  - NOx
  - NO2
  - NH4
  - DIP
  - LA
  - Color
  - TSS
  - Entero
  - TKN
  - TN
  - TP

# Field obervations list
field_obs:
  - Temperature, water
  - Dissolved oxygen (DO)
  - Salinity
  - pH
  - Turbidity

# Lab observations list
lab_obs:
  - Ammonium
  - Chlorophyll a
  - Enterococcus
  - Nitrate + Nitrite
  - Nitrite
  - Orthophosphate
  - Phosphorus
  - Total Kjeldahl nitrogen (Organic N & NH3)
  - Total suspended solids
  - True color


# Map characteristic names to units
unit_map:
  Water_Temp: "deg C"
  DO_Percent: "%"
  DO_Concentration: "mg/L"
  Conductivity: "µS/cm"
  Salinity: "PSU"
  Turbidity: "FNU"
  Secchi: "m"
  Chl_a: "ug/L"
  NOx: "ug/L"
  NO2: "ug/L"
  NH4: "ug/L"
  DIP: "mg/L"
  Color: "PCU"
  TSS: "mg/L"
  Entero: "MPN/100 mL"
  TP: "mg/L"
  TKN: "mg/L"
  TN: "mg/L"
  LA: "Kd"
  pH: ""


# Map characteristic names to WQX canonical names
param_name_map:
  Water_Temp: "Temperature, water"
  DO_Percent: "Dissolved oxygen (DO)"
  DO_Concentration: "Dissolved oxygen (DO)"
  Conductivity: "Conductivity"
  Salinity: "Salinity"
  Turbidity: "Turbidity"
  Secchi: "Depth, Secchi disk depth"
  Chl_a: "Chlorophyll a"
  NOx: "Nitrate + Nitrite"
  NO2: "Nitrite"
  NH4: "Ammonium"
  DIP: "Orthophosphate"
  Color: "True color"
  TSS: "Total suspended solids"
  Entero: "Enterococcus"
  TP: "Phosphorus"
  TN: "Total Nitrogen, mixed forms"
  TKN: "Total Kjeldahl nitrogen"
  LA: "Light attenuation coefficient"
  pH: "pH"

# columns from long_wq_table to copy into the WQX template
field_map:
  "Activity Depth/Height Measure": Water_Depth
  "Activity Start Date": Activity Start Date
  "Activity Start Time": Activity Start Time
  "Characteristic Name": Characteristic Name
  "Result Value": Result Value
  "Result Unit": Result_MeasureUnit

# default fixed values to apply to every row
fixed_fields:
  "Activity Depth/Height Unit": "m"
  "Project ID": "SRC-SRSWQ"
  "Activity Type": "Sample, water"
  "Activity Media Name": "Water"
  "Activity Start Time Zone": "America/Chicago"
  "Result Status ID": "Accepted"
  "Activity Group Type": "Monitoring"

# optional: you can define computed field templates
computed_fields:
   "Monitoring Location ID": "SRC-{Site}-22"

# filtered and unfiltered mappings 
filter_map:
  Ammonium: "Filtered, field"
  Chlorophyll a: "Unfiltered"
  Enterococcus: "Unfiltered"
  Nitrate + Nitrite: "Filtered, field"
  Nitrite: "Filtered, field"
  Orthophosphate: "Filtered, field"
  Phosphorus: "Unfiltered"
  Total Kjeldahl nitrogen (Organic N & NH3): "Unfiltered"
  Total Nitrogen, mixed forms : "Unfiltered"
  Total suspended solids: "Unfiltered"
  True color: "Filtered, field"

# result analytical method Id
analytical_methods_map:
  Ammonium: "CEDB ammonium-1"
  Chlorophyll a: "CEDB chla-1"
  Enterococcus: "ENTEROLERT"
  Nitrate + Nitrite: "CEDB nitrate and nitrite-1"
  Nitrite: "CEDB nitrite-1"
  Orthophosphate: "CEDB DIP-1"
  Phosphorus: "I-4650-03"
  Total Kjeldahl nitrogen (Organic N & NH3): "365.4"
  Total Nitrogen, mixed forms : "I-4650-03"
  Total suspended solids: "160.2"
  True color: "2120-C"


# YAML mapping between long_wq_table columns and template columns
column_map:
  # Activity metadata
  Site: "Monitoring Location ID"
  Activity_type: "Activity Type"
  Water_Depth: "Activity Depth/Height Measure"
  sample_equipment_name: "Sample Collection Equipment Name"
  sample_collection_comment: "Sample Collection Equipment Comment"
  `Activity Start Date`: "Activity Start Date"
  `Activity Start Time`: "Activity Start Time"
  method_speciation: "Method Speciation"

  # Result details
  `Result Value`: "Result Value"
  unit: "Result Unit"
  result_sample_fraction: "Result Sample Fraction"
  analytical_method_id: "Result Analytical Method ID"
  result_detection_type: "Result Detection/Quantitation Limit Type"
  result_detection_limit: "Result Detection/Quantitation Limit Measure"
  canonical_name: "Characteristic Name"

  # Optional / placeholders
  # These may need constants or NA fills in mutate()
  Project_ID: "Project ID"
  Activity_ID: "Activity ID (CHILD-subset)"
  Activity_ID_Parent: "Activity ID User Supplied (PARENTs)"
  Activity_Media_Name: "Activity Media Name"
  Result_Status_ID: "Result Status ID"
  Laboratory_Name: "Laboratory Name"
  Activity_Group_ID: "Activity Group ID"
  Activity_Group_Name: "Activity Group Name"